/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GPIO.h"

#define AHB1_BASE_ADDR	0x40020000
#define RCC_OFFSET_ADDR 0x3800
#define RCC_BASE_ADDR	(AHB1_BASE_ADDR + RCC_OFFSET_ADDR)
#define RCC_AHB1ENR		*(uint32_t *)(RCC_BASE_ADDR + 0x30)	// AHB1 enable register

void delay(uint32_t t);

int main(void)
{
	RCC_AHB1ENR |= (1<<0);	// GPIOA Clock Enable
	RCC_AHB1ENR |= (1<<2);	// GPIOC Clock Enable

//	GPIOA_MODER &= ~(1<<11); // GPIOA PA5 output mode
//	GPIOA_MODER |= (1<<10); // GPIOA PA5 output mode
//	GPIOA->MODER &= ~(1<<11); // GPIOA PA5 output mode
//	GPIOA->MODER |= (1<<10); // GPIOA PA5 output mode

	GPIO_Init(GPIOA, 5, OUTPUT);
	GPIO_Init(GPIOC, 10, INPUT);

    /* Loop forever */
	for(;;)
	{
		if(GPIO_Read(GPIOC, 10))
			GPIO_Write(GPIOA, 5, GPIO_SET);
		else
			GPIO_Write(GPIOA, 5, GPIO_RESET);

//		GPIO_Toggle(GPIOA, 5);
//		GPIOA->ODR ^= (1<<5);
//		delay(500);
	}
}

void delay(uint32_t t)
{
	uint32_t temp = 0;
	for (int i = 0; i < t; i++) {
		for (int j = 0; j < 1000; j++) {
			temp++;
		}
	}
}

